name: podcast_bot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - ffmpeg
  - pip
  - pip:
    - -r pytorch-requirements.txt
    - git+https://github.com/m-bain/whisperx.git
    - feedparser
    - requests
    - yt-dlp
    - pyannote.audio==3.3.2
    - python-dotenv

