name: podcast_bot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas           
  - pytorch==2.0.0
  - torchaudio==2.0.0
  - pytorch-cuda=11.8
  - ffmpeg
  - pip
  - pip:
    - git+https://github.com/m-bain/whisperx.git
    - feedparser
    - requests
    - pyannote.audio
    - python-dotenv

